cluster:
  name: cluster-name
  id: a7caff6f-3ac1-4f12-8e69-5ebce5e83692
  description: 'cluster description'

network:
  ip: 0.0.0.0
  httpServer:
    enable: true
    port: 21280
  httpsServer:
    enable: false
    port: 21281
    mutualTLS: false

serviceInfo:
  version: v1
  hostName: HostName
  serviceName: ether-faucet
  processName: ether-faucet
  ip: 127.0.0.1
  port: 21280
  tags:
    - microservice
    - typescript
    - docker
  id: 9af6d6e7-d58f-4a8c-88bf-e9fa239785f2

log:
  level: DEBUG

custom:
  faucet:
    # Faucet contract address
    faucetContractAddress: 'FAUCET_CONTRACT_ADDRESS'

    # Faucet token amount (unit: ether)
    faucetAmount: '5'

    # Withdraw by random operator, set 'true' to enable (Optional)
    randomFaucet: true

    # RESTFul API response code
    apiResponseCode:
      OK: 'YOUR_RESPONSE_CODE'
      ERROR: 'YOUR_RESPONSE_CODE'

    # Operator list
    operatorList:
      - address: 'OPERATOR_1_ADDRESS'
        keyStoreSK: ''
      - address: 'OPERATOR_2_ADDRESS'
        keyStoreSK: ''

  tx:
    # Transfer confirmations
    confirmations: 1

  # Default network
  defaultNetwork:
    # Chain name
    chain: polygon
    # Network name
    network: mumbai
    # Use provider pool
    providerPool: true

  networks:
    # Local Development
    dev:
      local:
        chainId: 666
        provider:
          - http://localhost:8545
        browser: http://localhost:4000

    # Ethereum
    ethereum:
      ropsten:
        chainId: 3
        provider:
          - 'YOUR PROVIDER'
        browser: https://ropsten.etherscan.io

      rinkeby:
        chainId: 4
        provider:
          - 'YOUR PROVIDER'
        browser: https://rinkeby.etherscan.io

      goerli:
        chainId: 5
        provider:
          - 'YOUR PROVIDER'
        browser: https://goerli.etherscan.io

    # Polygon
    # Ref: https://docs.polygon.technology/docs/develop/network-details/network
    polygon:
      mumbai:
        chainId: 80001
        provider:
          - https://rpc-mumbai.matic.today
          - https://matic-mumbai.chainstacklabs.com
        browser: https://mumbai.polygonscan.com

    # zkSync 2
    zkSync:
      # zkSync 2.0 (zkSync alpha testnet)
      # Ref: https://v2-docs.zksync.io/dev/testnet/important-links.html
      alpha:
        chainId: 280
        provider:
          - https://zksync2-testnet.zksync.dev
        browser: https://zksync2-testnet.zkscan.io
